### ISSUE TITLE
Default parameter of sigma in Heston process, CIR process

### ISSUE THREAD

**Issue by masanorihirano** [pfnet-research/pfhedge#203]
I think the default value of sigma in Heston class, Heston process generation, CIR process generation are too big.

Currently, sigma was set to 2.0.

```
from pfhedge.stochastic.cir import generate_cir
generate_cir(10,100, sigma=2.0)
generate_cir(10,100, sigma=0.2)
```
sigma=2.0 seems too big and makes many 0 as a result.
In Heston process, this means no volatility.
I think sigma=0.2 seems better.

https://doi.org/10.1007/978-3-319-05221-2_3
p.75 Fig. 3.1 seems a good reference for it.

**Comment by masanorihirano** [comment]
@simaki wrote in https://github.com/pfnet-research/pfhedge/pull/201:
I chose the default parameters as that in the experimental setup of [Deep Hedging](https://arxiv.org/abs/1802.03042) (eq. (5.2)). But I am also skeptical that it is a sensible value because it actually breaks the Feller condition and results in vanishing variances. I appreciate it if you could create a separate issue on that so we can make a further discussion.

**Comment by simaki** [comment]
A problem is, theoretically sensible parameters (i.e. parameters satisfying the Feller condition) may not reflect a typical situation in the market (cf. [CIRモデルとJCIRモデル - QuantCollege](https://quantcollege.net/cir%e3%83%a2%e3%83%87%e3%83%ab%e3%81%a8jcir%e3%83%a2%e3%83%87%e3%83%ab) for a case of CDS options). Conversely, parameters that fit the market are theoretically unhealthy and mess up generated time series. This has actually been my headache since I implemented HestonStock...

Another patch-up for this is to leave a note in the documentation that the default sigma is too big and makes many 0 as a result.

**Comment by masanorihirano** [comment]
The practical problem is, delta cannot be calculated when the volatility is 0.
Delta is calculated via Black sholes' d1.
Thus, 0-volatility disable to calculate the delta and cause a fatal error of pfhedge.

**Comment by simaki** [comment]
Oh, yeah, that really makes sense. Though it's Heston it would be common to apply the BS formula for delta, implied volatility and so and it's weird that the default value brings errors.

Let's change the default value to `sigma=0.2`. Could you make a PR?
